# Generated by Django 3.0.1 on 2021-02-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='flight',
            new_name='flights',
        ),
    ]
