# Generated by Django 3.1.7 on 2021-03-03 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=40)),
                ('is_sep_by_prod_type', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GroupCategoryMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_group', to='zebra.activitygroup')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_name', to='zebra.categories')),
            ],
        ),
        migrations.CreateModel(
            name='GroupCatTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groucattypes_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='KpiDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulae', models.CharField(max_length=5)),
                ('kpi_group_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_group_de', to='zebra.groupcategorymatrix')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=50)),
                ('lang_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=3)),
                ('product_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=65)),
                ('site_name', models.CharField(max_length=65)),
                ('country', models.CharField(max_length=50)),
                ('sbu', models.CharField(max_length=50)),
                ('eam_no', models.CharField(max_length=12)),
                ('shop', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteLanguageCountryMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('country_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_master', to='zebra.country')),
                ('site_lang_matrix_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_lang_matrix_name', to='zebra.language')),
                ('site_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_master', to='zebra.site')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('is_working_day', models.BooleanField()),
                ('site_work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_workday', to='zebra.site')),
            ],
        ),
        migrations.CreateModel(
            name='UserSiteLanguageCountryMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_relation', to='zebra.role')),
                ('site_lang_coun_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_lang_count_matrix', to='zebra.sitelanguagecountrymatrix')),
                ('user_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSiteMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='zebra.products')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='zebra.site')),
            ],
        ),
        migrations.CreateModel(
            name='KpiTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('kpi_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_def', to='zebra.kpidefinition')),
                ('site_language_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_language_count', to='zebra.sitelanguagecountrymatrix')),
            ],
        ),
        migrations.CreateModel(
            name='KpiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(auto_now_add=True)),
                ('kpi_data_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_data_name', to='zebra.usersitelanguagecountrymatrix')),
                ('status_data_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_data_name', to='zebra.status')),
            ],
        ),
        migrations.AddField(
            model_name='groupcategorymatrix',
            name='group_category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_category_name', to='zebra.groupcattypes'),
        ),
    ]
