# Generated by Django 3.1.7 on 2021-03-03 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(default='cc_controller', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='zebra.role')),
            ],
        ),
        migrations.AlterField(
            model_name='usersitelanguagecountrymatrix',
            name='user_relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relation', to='zebra.user'),
        ),
    ]
