# Generated by Django 3.1.7 on 2021-03-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0003_auto_20210304_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpidata',
            old_name='year',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='kpidata',
            old_name='status_data_name',
            new_name='status_name',
        ),
        migrations.AlterField(
            model_name='kpidata',
            name='kpi_data_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_data_name', to='zebra.sitelanguagecountrymatrix'),
        ),
    ]
