# Generated by Django 3.0.1 on 2021-02-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('FASHION', 'Fashion'), ('ELECT', 'Electronics'), ('TOYS', 'Toys'), ('ANT', 'Antique'), ('HOME', 'Home'), ('OTHERS', 'Others')], default=7, max_length=10),
        ),
    ]
