# Generated by Django 3.0.1 on 2021-02-22 13:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210222_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FASHION', 'Fashion'), ('ELECT', 'Electronics'), ('TOYS', 'Toys'), ('ANT', 'Antique'), ('HOME', 'Home'), ('OTHERS', 'Others')], max_length=34),
        ),
    ]
