# Generated by Django 3.0.1 on 2021-02-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='user_name', max_length=255),
        ),
    ]
