# Generated by Django 3.0.1 on 2021-02-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comment_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_added',
        ),
    ]
