# Generated by Django 3.0.1 on 2021-02-24 21:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_comment_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listing',
        ),
        migrations.AddField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 24, 21, 22, 30, 984739, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
