# Generated by Django 3.0.1 on 2021-02-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='the blog', max_length=65),
        ),
    ]
