# Generated by Django 3.0.1 on 2021-02-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=65)),
                ('site_name', models.CharField(max_length=65)),
                ('country', models.CharField(max_length=50)),
                ('sbu', models.CharField(max_length=50)),
                ('eam_no', models.CharField(max_length=12)),
                ('shop', models.BooleanField()),
            ],
        ),
    ]
