# Generated by Django 3.0.1 on 2021-02-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zebrakpi', '0002_sites_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sites',
        ),
    ]
