# Generated by Django 3.0.1 on 2021-02-26 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zebrakpi', '0002_auto_20210226_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=3)),
                ('product_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='zebrakpi.Products')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='zebrakpi.Sites')),
            ],
        ),
    ]
