# Generated by Django 3.0.1 on 2021-02-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zebrakpi', '0003_products_productsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=40)),
                ('is_sep_by_prod_type', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='GroupCatTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groucattypes_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameModel(
            old_name='ProductSite',
            new_name='ProductSiteMatrix',
        ),
        migrations.CreateModel(
            name='GroupCategoryMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_group', to='zebrakpi.ActivityGroup')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_name', to='zebrakpi.Categories')),
                ('group_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_category_name', to='zebrakpi.GroupCatTypes')),
            ],
        ),
    ]
