# Generated by Django 3.0.1 on 2021-02-26 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zebrakpi', '0004_auto_20210226_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=50)),
                ('lang_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Sites',
            new_name='Site',
        ),
        migrations.CreateModel(
            name='SiteLanguageMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('country_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_master', to='zebrakpi.Country')),
                ('site_lang_matrix_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_lang_matrix_name', to='zebrakpi.Language')),
                ('site_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_master', to='zebrakpi.Site')),
            ],
        ),
    ]
