# Generated by Django 3.0.1 on 2021-02-26 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zebrakpi', '0005_auto_20210226_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulae', models.CharField(max_length=5)),
                ('kpi_group_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_group_de', to='zebrakpi.GroupCategoryMatrix')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='SiteLanguageMatrix',
            new_name='SiteLanguageCountryMatrix',
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('is_working_day', models.BooleanField()),
                ('site_work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_workday', to='zebrakpi.Site')),
            ],
        ),
        migrations.CreateModel(
            name='UserSiteLanguageCountryMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_relation', to='zebrakpi.Role')),
                ('site_lang_coun_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_lang_count_matrix', to='zebrakpi.SiteLanguageCountryMatrix')),
                ('user_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KpiTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('kpi_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_def', to='zebrakpi.KpiDefinition')),
                ('site_language_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_language_count', to='zebrakpi.SiteLanguageCountryMatrix')),
            ],
        ),
        migrations.CreateModel(
            name='KpiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(auto_now_add=True)),
                ('kpi_data_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_data_name', to='zebrakpi.SiteLanguageCountryMatrix')),
                ('status_data_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_data_name', to='zebrakpi.Status')),
            ],
        ),
    ]
