# Generated by Django 3.0.1 on 2021-02-25 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('category', models.CharField(choices=[('FASHION', 'Fashion'), ('ELECT', 'Electronics'), ('TOYS', 'Toys'), ('ANT', 'Antique'), ('HOME', 'Home'), ('OTHERS', 'Others')], default=7, max_length=10)),
                ('startbidprice', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
